### ISSUE TITLE
fbtomate project

### ISSUE THREAD

**Issue by ttpopza** [TetsuyaNarra/fbtomate#1]
Hello! What you've done is truly remarkable. For your fbtomate project, could you please add the capability to upload multiple images? I would greatly appreciate it if you could. It would be incredibly beneficial for many people.

**Comment by TetsuyaNarra** [comment]
No worries, I got that on the list. Thanks for your interest on my project.

**Comment by ttpopza** [comment]
Wow Spectacular!

**Comment by TetsuyaNarra** [comment]
Hi, just want to let you know that I have finished this feature to upload multiple images, feel free to use my software. Enjoy :)

**Comment by ttpopza** [comment]
Currently, I've encountered an error during the image upload process. The upload cannot be completed because when the code searches for the xpath of the upload button on Facebook, it brings up a window to manually select the file. This prevents the automatic upload by specifying the file location.

**Comment by TetsuyaNarra** [comment]
What OS you are using? What version of python you are using? and can you screenshot your terminal after your session.

**Comment by TetsuyaNarra** [comment]
I'll mark this as closed due to tests I have conducted, there's no such issues I have encountered.
